### ISSUE TITLE
How about ATTiny4313 support?

### ISSUE THREAD

**Issue by Isaac96** [baerwolf/USBaspLoader#13]
Will the USBASPLoader fit in 2K?
The 4313 has no bootloader section.

**Comment by baerwolf** [comment]
Hi and thx for your request.
In principle USBaspLoader fits into 2KB of BLS (bootloader section).
(ATmega8 also has only 2KB of it and it works...)
At the moment USBaspLoader doesn't support ATtiny, but I will go find out if it is possible to support on the short notice.
I will be back soon with new information.

BR Stephan

**Comment by Isaac96** [comment]
I think the 4313 has 256B of RAM.

**Comment by baerwolf** [comment]
OK and hi again.

I did some research about the ATtiny4313.
Except the SRAM might be a bit small, the device does not support booloaders at all.
(Means it hasn't extra interrupts.) Also the flash is very limited.
If you like I can cite the datasheet in this...

Perhaps I can convince you using atmega8 or its siblings?
It is only a bit bigger but most likely cheaper and more powerful.

As a small gift compensating these bad new, I would like to donate you a tinyUSBboard kit - if you like and if you send me your address.

BR Stephan

p.s.: With your OK I will close this issue

**Comment by Isaac96** [comment]
Yeah, I have a couple 4313's hanging around and don't want to pay more than the cost of a chip for shipping.

**Comment by baerwolf** [comment]
>EDIT What is the TinyUSBboard?
Its the reference hardware/project for the USBaspLoader:
http://matrixstorm.com/avr/tinyusbboard/
