### ISSUE TITLE
Help on options

### ISSUE THREAD

**Issue by dvv** [baerwolf/USBaspLoader#16]
Hello!

What set of options should I have enabled to achieve the following behavior:
1. on reset enter usbasp mode
2. after 3 seconds of inactivity go to main app
3. if there were activity and usbasp were used to upload the firmware, restart

Right now I use the following `$(DEFINES)`
```c
-DCONFIG_NO__CHIP_ERASE -DCONFIG_NO__ONDEMAND_PAGEERASE -DCONFIG_NO__PRESERVE_WATCHDOG -DCONFIG_HAVE__BOOTLOADER_ALWAYSENTERPROGRAMMODE -DCONFIG_BOOTLOADER_LOOPCYCLES_TIMEOUT=16 -DCONFIG_HAVE__BOOTLOADER_ABORTTIMEOUTONACT -DBOOTLOADER_CAN_EXIT=1 -DHAVE_BOOTLOADER_HIDDENEXITCOMMAND=1 -DCONFIG_HAVE__BOOTLOADER_IGNOREPROGBUTTON
```

but it fails to do point 3.

Or, if I could achieve that with `HAVE_BOOTLOADER_HIDDENEXITCOMMAND`, how to issue the exit sequence via `avrdude`?

TIA,
--Vladimir

**Comment by baerwolf** [comment]
Hi Vladimir

For

1.) enable "CONFIG_HAVE__BOOTLOADER_ALWAYSENTERPROGRAMMODE"
2.) enable "CONFIG_BOOTLOADER_LOOPCYCLES_TIMEOUT=16"
3.) DO NOT enable "CONFIG_HAVE__BOOTLOADER_ABORTTIMEOUTONACT"
(do use timeout also after activity)

4.) if you do not have prog-button enable "CONFIG_HAVE__BOOTLOADER_IGNOREPROGBUTTON"

BR Stephan

**Comment by dvv** [comment]
Works. Thank you!
