### ISSUE TITLE
Buil Not fit into your MCUs bootloader section

### ISSUE THREAD

**Issue by TienHuyIoT** [baerwolf/USBaspLoader#18]
Hi,
I builed your project. But not fit into bootloader section.
My device: atmega328
And Buil
!!!ATTANTION!!!
(data+text) MUST fit into your MCUs bootloader section
.
   text	   data	    bss	    dec	    hex	filename
   4102	      6	     57	   4165	   1045	main.elf

Data+text = 4108 while Bootloader is 4096.
How to fix problem. Tks!

**Comment by baerwolf** [comment]
Hi and sorry for my extreme late and overdue response.

First I recommend using an other (newer?) toolchain to compile. Newer gcc tend to optimize more agressivly.
If other gcc is no option for you, please start turning features off.

BR
